"""PyTorch .pt → ONNX → TFLite 변환.

vela 호환 fp32 TFLite 산출. (Ethos-U 최적 성능을 위해서는 INT8 양자화가 권장되지만
calibration 데이터가 필요하므로 검증용으로는 fp32만 수행.)
"""
import shutil
import sys
from pathlib import Path

import torch

INPUT_PT = Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/compressed_model.pt")
OUTPUT_TFLITE = Path(sys.argv[2] if len(sys.argv) > 2 else "/output/model.tflite")
INPUT_SHAPE = tuple(int(x) for x in (sys.argv[3].split(",") if len(sys.argv) > 3 else ["1", "3", "224", "224"]))

print(f"[convert] input={INPUT_PT}  output={OUTPUT_TFLITE}  shape={INPUT_SHAPE}")
OUTPUT_TFLITE.parent.mkdir(parents=True, exist_ok=True)

# 1. PyTorch → ONNX
print("[convert] step 1/2: PyTorch → ONNX")
model = torch.load(str(INPUT_PT), map_location="cpu", weights_only=False)
model.eval()
onnx_path = INPUT_PT.with_suffix(".onnx")
dummy = torch.randn(*INPUT_SHAPE)
torch.onnx.export(
    model,
    dummy,
    str(onnx_path),
    input_names=["input"],
    output_names=["output"],
    opset_version=13,
)
print(f"[convert] ONNX saved → {onnx_path}  ({onnx_path.stat().st_size / 1024:.1f} KB)")

# 2. ONNX → TFLite (onnx2tf)
print("[convert] step 2/2: ONNX → TFLite (onnx2tf)")
import onnx2tf

work_dir = Path("/tmp/tflite_out")
shutil.rmtree(work_dir, ignore_errors=True)
work_dir.mkdir(parents=True, exist_ok=True)

onnx2tf.convert(
    input_onnx_file_path=str(onnx_path),
    output_folder_path=str(work_dir),
    output_signaturedefs=True,
    not_use_onnxsim=True,
    not_use_opname_auto_generate=True,
    output_h5=False,
    output_keras_v3=False,
)

# 결과 .tflite 중 가장 적절한 것을 선택
candidates = list(work_dir.glob("*.tflite"))
print(f"[convert] generated candidates: {[c.name for c in candidates]}")
if not candidates:
    raise RuntimeError("No tflite output generated by onnx2tf")

# float32 우선, 없으면 첫 번째
preferred = next((c for c in candidates if "float32" in c.name), None) or candidates[0]
shutil.copy(preferred, OUTPUT_TFLITE)
print(f"[convert] copied {preferred} → {OUTPUT_TFLITE}  ({OUTPUT_TFLITE.stat().st_size / 1024:.1f} KB)")
print("[convert] OK")
